# Generated by Django 2.0.1 on 2018-01-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operand1', models.CharField(max_length=15)),
                ('operator', models.CharField(max_length=1)),
                ('operand2', models.CharField(max_length=15)),
            ],
        ),
    ]
